name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Workflow sẽ chạy khi đẩy code lên nhánh main.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Chọn phiên bản Ruby phù hợp

      # Bước 3: Cài đặt các gói cần thiết
      - name: Install dependencies
        run: |
          bundle install

      # Bước 4: Build website
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      # Bước 5: Deploy trực tiếp lên nhánh main
      - name: Copy files to main branch root
        run: |
          mv _site/* ./  # Chuyển nội dung từ _site ra gốc nhánh main
          git add .
          git commit -m "Deploy site" || echo "No changes to deploy"
          git push origin main
