name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Thay 'main' bằng nhánh chính của bạn, nếu khác.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Chọn phiên bản Ruby, thường là 3.x

      # Bước 3: Cài đặt các gói cần thiết
      - name: Install dependencies
        run: |
          bundle install

      # Bước 4: Build website
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      # Bước 5: Deploy tới GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
